sca:
  appUrl: ${SCA_APP_URL}
  apiUrl: https://api.scacheckmarx.com
  accessControlUrl: https://platform.checkmarx.net
  tenant: ${SCA_TENANT}
  username: ${SCA_USERNAME}
  password: ${SCA_PASSWORD}
